Update pom.xml
getgauge-contrib/gauge-maven-plugin pull request #85
Opened 2024-01-22 21:46 UTC by deepesh1511

Updating maven version to latest

2024-02-14 19:53 UTC, zabil commented
@deepesh1511 can you please sign the DCO? Follow instructions here https://github.com/getgauge-contrib/gauge-maven-plugin/pull/85/checks?check_run_id=20747451448

2024-02-15 00:56 UTC, chadlwilson requested changes

2024-02-15 00:56 UTC, chadlwilson commented on pom.xml
> +        <maven.version>4.0.0-alpha-12</maven.version>
I don't really understand how this solves the problem but we shouldnt depend on an unreleased alpha version of Maven.

`3.9.6` is the latest Maven release.

2024-02-15 03:30 UTC, chadlwilson commented
The root of the problem here is likely that these Maven dependencies should be in the `provided` scope for a Maven plugin, not compile time dependencies as they currently are. This was they are supplied by Maven and not resolved by the plugin.

For example, this is how the dependency-check maven is set up: https://mvnrepository.com/artifact/org.owasp/dependency-check-maven/9.0.9 or something core like the [maven-gpg-plugin](https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-gpg-plugin/3.1.0).

An alternate/cleaner way to fix this is at https://github.com/getgauge-contrib/gauge-maven-plugin/pull/87 (despite being an org member, I don't seem to have permissions this particular repository)

2024-03-26 15:38 UTC, haroon-sheikh commented
The changes have been updated as part of https://github.com/getgauge-contrib/gauge-maven-plugin/pull/87

2024-03-26 15:38 UTC, closed without merging